### ISSUE TITLE
ASTER - publicly available dataset 

### ISSUE THREAD

**Issue by rmkorr** [cogeotiff/rio-tiler-pds#51]
The Advanced Spaceborne Thermal Emission and Reflection Radiometer (ASTER) satellite is a publicly available dataset with 3 VNIR, 6 SWIR, and 5 thermal bands available both through Google Earth Engine and AWS. Data collected from this platform are extensively used in the geosciences and environmental monitoring. I would like to request this dataset be added to rio-tiler-pds.

AWS id = arn:aws:s3:::terrafusiondatasampler
GEE id = ASTER/AST_L1T_003

Web resources:
https://registry.opendata.aws/terrafusion/
https://developers.google.com/earth-engine/datasets/catalog/ASTER_AST_L1T_003#description

**Comment by vincentsarago** [comment]
Hi @rmkorr 
thanks for the issue.

I gave a quick look at the dataset (or mostly at the documentation, because I couldn't find any data). The first major problem is that the data is stored as HDF5 not as a pure cloud optimized dataset.  

> AWS S3 Public Bucket Containing Terra Basic Fusion Hierarchical Data Format 5 (HDF5) files

While you can in theory access HDF5 remotely, it is not as smooth as other format and might required a specific GDAL build. 

@rmkorr could you be able to share a s3 url for a specific data ?

**Comment by vincentsarago** [comment]
stale
