### ISSUE TITLE
Scene B3DA causing error with no /bounds

### ISSUE THREAD

**Issue by jonaraphael** [cogeotiff/rio-tiler-pds#78]
Our titiler instance fails when requesting bounds for the following scene:
S1A_S3_GRDH_1SDV_20230807T171941_20230807T172010_049772_05FC2A_B3DA

The object itself is rather strange looking in Scihub. With some weird sort of value-threshold feathering happening beyond the edge of what I would call the bounds of the image.
![image](https://github.com/cogeotiff/rio-tiler-pds/assets/1420607/2b4df60d-4d9b-4b74-abcc-d0a09d02a1f9)

**Comment by jonaraphael** [comment]
New example with the same behavior:
S1A_S1_GRDH_1SDV_20230809T020729_20230809T020754_049792_05FCE6_1175

Notes:
• This one does not have that strange feathering on its edges
• This one is not close to the anti-meridian
• This one is an S1A_S1, whereas the first example was an S1A_S3

**Comment by vincentsarago** [comment]
🤔 the issue is because the ID is invalid, because we only accept mode (`beam`) `IW` or `EW`. The beam `S1` or `S3` is something new to me. 

oh, those are `stripmap` modes, which are slightly different from Interferometric modes: https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/acquisition-modes/stripmap

I thing there is no real blocker from rio-tiler-pds side to allow those datasets!

**Comment by jonaraphael** [comment]
Amazing! Thank you so much for including these!
